version: "3"

services:
  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-postgres}"
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - todoapp-postgres:/var/lib/postgresql/data
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    healthcheck:
      test: pg_isready -U postgres
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  backend:
    build:
      context: ./todo-backend
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: todo_app
    ports:
      - "3000:3000"
  web:
    build:
      context: ./todo-web
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"

volumes:
  todoapp-postgres:
