version: '3'

services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: '${PGUSER:-postgres}'
      POSTGRES_PASSWORD: '${PGPASSWORD:-postgres}'
    ports:
      - '${PGPORT:-5432}:5432'
    volumes:
      - todoapp-postgres:/var/lib/postgresql/data
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
volumes:
  todoapp-postgres:
